speed_multiplexer:
  name: "speed_mux"
  type: "Twist"
  frequency_ms: 1000
  timeout: 0.5
  topics:
    output:
      topic: "/cmd_vel"
    inputs:
      input_1:
        topic: "/manual/cmd_vel"
        priority: 20
      input_2:
        topic: "/auto/cmd_vel"
        priority: 10
      input_3:
        topic: "/safety/cmd_vel"
        priority: 30

brake_multiplexer:
  name: "/brake_mux"
  type: "Float64"
  frequency_ms: 100
  timeout: 0.5
  topics:
    output:
      topic: "/cmd_brakes"
    inputs:
      input_1:
        topic: "/auto/cmd_brakes"
        priority: 10
      input_2:
        topic: "/manual/cmd_brakes"
        priority: 20
      input_3:
        topic: "/safety/cmd_brakes"
        priority: 30